name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t hanusahani4/rdvisioncrmui .
      - name: Publish image to docker hub
        run: docker push hanusahani4/rdvisioncrmui:latest   

  deploy: 
    needs: build
    runs-on: [aws-ec2]    
    steps:
      - name: Pull image from docker hub
        run: docker pull hanusahani4/rdvisioncrmui:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer || true
      - name: Run docker container
        run: docker run -d -p 443:3000 --name reactContainer hanusahani4/rdvisioncrmui
